name: Foundry Setup

on:
  workflow_call:

jobs:
  pre-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Foundry version
        id: set-version
        run: echo "FOUNDRY_VERSION=nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9" >> "$GITHUB_ENV"

  setup:
    runs-on: ubuntu-latest
    needs: pre-setup
    outputs:
      key: ${{ steps.set-key.outputs.key }}
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FOUNDRY_VERSION }}
      - name: Print forge version
        run: forge --version
      - name: Save Foundry cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.foundry
          key: ${{ runner.os }}-foundry-${{ env.FOUNDRY_VERSION }}
      - name: Save key
        id: set-key
        run: echo "key=${{ runner.os }}-foundry-${{ env.FOUNDRY_VERSION }}" >> "$GITHUB_OUTPUT"
