name: Foundry Setup

on:
  workflow_call:
    outputs:
      installation_dir:
        description: "The installation directory of Foundry toolchain"
        value: ${{ jobs.setup.outputs.installation_dir }}
      key:
        description: "The cache key for Foundry toolchain"
        value: ${{ jobs.setup.outputs.key }}

jobs:
  pre-setup:
    runs-on: ubuntu-latest
    outputs:
      foundry_version: ${{ steps.set-version.outputs.foundry_version }}
    steps:
      - name: Set Foundry version
        id: set-version
        run: |
          echo "foundry_version=nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9" >> "$GITHUB_OUTPUT"

  setup:
    runs-on: ubuntu-latest
    needs: pre-setup
    outputs:
      key: ${{ steps.set-key.outputs.key }}
      installation_dir: ${{ steps.find-path.outputs.installation_dir }}
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ needs.pre-setup.outputs.foundry_version }}
      - name: Print forge version
        run: forge --version
      # Unfortunately, the `foundry-toolchain` action installs it in a randomly generated location, so we must determine it ourselves
      - name: Determine Foundry installation path
        id: find-path
        run: |
          installation_path=$(which forge)
          installation_dir=$(dirname $installation_path)
          echo "installation_dir=$installation_dir" >> "$GITHUB_OUTPUT"
      - name: Cached Foundry toolchain
        uses: actions/cache/save@v3
        with:
          path: ${{ steps.find-path.outputs.installation_dir }}
          key: ${{ runner.os }}-foundry-${{ needs.pre-setup.outputs.foundry_version }}
      - name: Set key
        id: set-key
        run: |
          echo "key=${{ runner.os }}-foundry-${{ needs.pre-setup.outputs.foundry_version }}" >> "$GITHUB_OUTPUT"
