name: Foundry Setup

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ inputs.version }}

      - name: Print forge version
        run: forge --version

      - name: Save Foundry cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.foundry
          key: ${{ runner.os }}-foundry-${{ inputs.version }}
