name: Foundry Setup

on:
  workflow_call:

jobs:
  pre-setup:
    runs-on: ubuntu-latest
    outputs:
      foundry_version: ${{ steps.set-version.outputs.foundry_version }}
    steps:
      - name: Set Foundry version
        id: set-version
        run: |
          echo "foundry_version=nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9" >> "$GITHUB_OUTPUT"

  setup:
    runs-on: ubuntu-latest
    needs: pre-setup
    outputs:
      key: ${{ steps.set-key.outputs.key }}
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ needs.pre-setup.outputs.foundry_version }}
      - name: Print forge version
        run: forge --version
      - name: Save Foundry cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.foundry
          key: ${{ runner.os }}-foundry-${{ needs.pre-setup.outputs.foundry_version }}
      - name: Save key
        id: set-key
        run: |
          echo "key=${{ runner.os }}-foundry-${{ needs.pre-setup.outputs.foundry_version }}" >> "$GITHUB_OUTPUT"
